#pragma once
// ---------------------------------------------------------------------------
// Levoit Sprout — SPIFFS audio playback over I2S
// Public API declarations — implementation in levoit_audio.cpp
// ---------------------------------------------------------------------------

#include "esphome/core/component.h"
#include "esphome/components/select/select.h"
#include <stdint.h>
#include <stddef.h>

namespace levoit_audio {

class LevoitAudio : public esphome::Component {
 public:
  void setup() override;
  float get_setup_priority() const override { return esphome::setup_priority::HARDWARE; }
  void add_sound(const char *file, const char *name);
};

// Select entity generated by __init__.py — options are static string literals
// set at code-gen time via initializer_list (no runtime set_options needed).
class LevoitAudioSelect : public esphome::select::Select, public esphome::Component {
 public:
  void dump_config() override;
 protected:
  void control(const std::string &value) override;
};

}  // namespace levoit_audio

// ---------------------------------------------------------------------------
// Free functions — callable from ESPHome lambdas
// ---------------------------------------------------------------------------
void levoit_audio_setup();
void levoit_audio_play(uint8_t index, bool loop = false);
void levoit_audio_stop();
void levoit_audio_set_loop(bool loop);
bool levoit_audio_is_looping();
void levoit_audio_set_volume(uint8_t vol);
uint8_t levoit_audio_get_volume();
bool levoit_audio_is_playing();
int  levoit_audio_current_index();
size_t levoit_audio_sound_count();
const char *levoit_audio_sound_name(size_t index);
